apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: dummy-data-producer
  namespace: kafka
  labels:
    strimzi.io/cluster: demo-kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource: { type: topic, name: tp.observability.logs.encrypted, patternType: literal }
        operations: [Describe, Write]
  quotas:
    producerByteRate: 2097152
    requestPercentage: 30
