apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: log-processor
  labels:
    strimzi.io/cluster: demo-kafka
spec:
  authentication:
    type: tls                      # el User Operator genera el Secret con el certificado
  authorization:
    type: simple
    acls:
      - resource: { type: topic, name: tp.observability.logs.encrypted, patternType: literal }
        operations: [Describe, Read]
      - resource: { type: topic, name: tp.observability.logs.masked, patternType: literal }
        operations: [Describe, Write]
      - resource: { type: topic, name: tp.observability.logs.encrypted.dlq, patternType: literal }
        operations: [Describe, Write]
      - resource: { type: group, name: log-processor-group, patternType: literal }
        operations: [Read]
  quotas:
    producerByteRate: 2097152
    consumerByteRate: 5242880
    requestPercentage: 30
    controllerMutationRate: 5
